from time import sleep


def blank(i):
  blank = f"""
  ------------------------------------------------------------------
  ------------------------------------------------------------------
  ------------------------------------------------------------------
  -----------------------{red_star(i, 18)}{red_star(i, 18)}{red_star(i, 18)}{red_star(i, 18)}{red_star(i, 18)}{red_star(i, 18)}{red_star(i, 18)}{red_star(i, 18)}{red_star(i, 18)}-----------------{red_star(i, 18)}{red_star(i, 18)}{red_star(i, 18)}{red_star(i, 18)}{red_star(i, 18)}{red_star(i, 18)}{red_star(i, 18)}{red_star(i, 18)}{red_star(i, 18)}---------
  ---------------------{red_star(i, 17)}{red_star(i, 17)}{red_star(i, 17)}{red_star(i, 17)}{red_star(i, 17)}{red_star(i, 17)}{red_star(i, 17)}{red_star(i, 17)}{red_star(i, 17)}{red_star(i, 17)}{red_star(i, 17)}{red_star(i, 17)}{red_star(i, 17)}-------------{red_star(i, 17)}{red_star(i, 17)}{red_star(i, 17)}{red_star(i, 17)}{red_star(i, 17)}{red_star(i, 17)}{red_star(i, 17)}{red_star(i, 17)}{red_star(i, 17)}{red_star(i, 17)}{red_star(i, 17)}{red_star(i, 17)}{red_star(i, 17)}-------
  -------------------{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}---------{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}{red_star(i, 16)}-----
  -----------------{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}-------{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}{red_star(i, 15)}----
  ----------------{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}---{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}{red_star(i, 14)}---
  ---------------{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}-{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}{red_star(i, 13)}--
  ---------------{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}{red_star(i, 12)}--
  ---------------{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}{red_star(i, 11)}--
  ----------------{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}Jouko 40v{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}{red_star(i, 10)}---
  ------------------{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}{red_star(i, 9)}-----
  --------------------{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}{red_star(i, 8)}-------
  -----------------------{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}{red_star(i, 7)}---------
  --------------------------{red_star(i, 6)}{red_star(i, 6)}{red_star(i, 6)}{red_star(i, 6)}{red_star(i, 6)}{red_star(i, 6)}{red_star(i, 6)}{red_star(i, 6)}{red_star(i, 6)}{red_star(i, 6)}{red_star(i, 6)}{red_star(i, 6)}{red_star(i, 6)}{red_star(i, 6)}{red_star(i, 6)}{red_star(i, 6)}{red_star(i, 6)}{red_star(i, 6)}{red_star(i, 6)}{red_star(i, 6)}{red_star(i, 6)}{red_star(i, 6)}{red_star(i, 6)}{red_star(i, 6)}{red_star(i, 6)}{red_star(i, 6)}{red_star(i, 6)}{red_star(i, 6)}{red_star(i, 6)}------------
  -----------------------------{red_star(i, 5)}{red_star(i, 5)}{red_star(i, 5)}{red_star(i, 5)}{red_star(i, 5)}{red_star(i, 5)}{red_star(i, 5)}{red_star(i, 5)}{red_star(i, 5)}{red_star(i, 5)}{red_star(i, 5)}{red_star(i, 5)}{red_star(i, 5)}{red_star(i, 5)}{red_star(i, 5)}{red_star(i, 5)}{red_star(i, 5)}{red_star(i, 5)}{red_star(i, 5)}{red_star(i, 5)}{red_star(i, 5)}{red_star(i, 5)}{red_star(i, 5)}---------------
  -------------------------------{red_star(i, 4)}{red_star(i, 4)}{red_star(i, 4)}{red_star(i, 4)}{red_star(i, 4)}{red_star(i, 4)}{red_star(i, 4)}{red_star(i, 4)}{red_star(i, 4)}{red_star(i, 4)}{red_star(i, 4)}{red_star(i, 4)}{red_star(i, 4)}{red_star(i, 4)}{red_star(i, 4)}{red_star(i, 4)}{red_star(i, 4)}{red_star(i, 4)}------------------
  ----------------------------------{red_star(i, 3)}{red_star(i, 3)}{red_star(i, 3)}{red_star(i, 3)}{red_star(i, 3)}{red_star(i, 3)}{red_star(i, 3)}{red_star(i, 3)}{red_star(i, 3)}{red_star(i, 3)}{red_star(i, 3)}{red_star(i, 3)}{red_star(i, 3)}--------------------
  -------------------------------------{red_star(i, 2)}{red_star(i, 2)}{red_star(i, 2)}{red_star(i, 2)}{red_star(i, 2)}{red_star(i, 2)}{red_star(i, 2)}-----------------------
  ----------------------------------------{red_star(i, 1)}--------------------------
  -------------------------------------------------------------------
  """
  print(blank.replace("-", " "))

def red_star(i, light_up):
  if i >= light_up:
    return "\033[91m*\033[0m"
  else:
    return " "

while True:
  for i in range(11):
    for i in range(19):
      blank(i)
      sleep(0.1)
    for i in range(6):
      sleep(1)
      blank(20)
      sleep(1)
      blank(0)
    blank(20)
    sleep(5)